version: '3'
services: 
  web:
    image: node-dashboard
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: db-dashboard
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dashboard
      - ENV MYSQL_USER=monty
      - ENV MYSQL_PASSWORD=monty
      - MYSQL_ROOT_PASSWORD=mdp