version: '3'
services: 
    web:
        # image: node-dashboard
        build: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/usr/src/app/
            # - /usr/src/app/node_modules
        working_dir: /usr/src/app
        user: "1000"
        container_name: backend
    frontend: 
        # image: anuglar
        build: ./frontend
        volumes:
            - ./frontend/:/app
        ports:  
            - "4200:4200"
        container_name: frontend
    database:
        build: ./database
        ports:
            - "3306:3306"
        volumes:
            - /database/data:/var/lib/mysql:rw
        #user: "1000"
        container_name: database


# - /usr/src/app/node_modules
