version: '3'
services:
  weather-service:
    build: ./backend/weather
    ports:
        - "${PORT_WEATHER_SERVICE}:${PORT_WEATHER_SERVICE}"
    volumes:
        - ./backend/weather:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    container_name: weatherServcie
  crypto-service:
    build: ./backend/cryptocurrency
    ports:
        - "${PORT_CRYPTO_SERVICE}:${PORT_CRYPTO_SERVICE}"
    volumes:
        - ./backend/cryptocurrency:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    environment:
        - MARIADB_HOST=database
        - MARIADB_PORT_NUMBER=3308
        - MARIADB_USER=monty
        - MARIADB_PASSWORD=monty
        - MARIADB_DATABASE=crypto
    user: "0"
    depends_on:
        - dbcrypto
    container_name: cryptoServcie
  user-service:
    build: ./backend/user
    ports:
        - "${PORT_USER_SERVICE}:${PORT_USER_SERVICE}"
    volumes:
        - ./backend/user:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    environment:
        - MARIADB_HOST=database
        - MARIADB_PORT_NUMBER=3306
        - MARIADB_USER=monty
        - MARIADB_PASSWORD=monty
        - MARIADB_DATABASE=dashboard
    user: "1000"
    container_name: userService
    depends_on:
        - database
    links:
        - database:database
  frontend: 
    build: ./frontend
    volumes:
        - ./frontend/:/app
    ports:  
        - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    container_name: frontend
  database:
    build: ./database
    ports:
        - "${PORT_DATABASE}:${PORT_DATABASE}"
    expose:
        - "${PORT_DATABASE}"
    command: mysqld
    volumes:
      - ./database/data:/var/lib/mysql:rw
    user: "1000"
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=dashboard
        - MARIADB_PORT=3306
        - MARIADB_USER=monty
        - MARIADB_PASSWORD=monty
    container_name: database
  dbcrypto:
    build: ./database/crypto
    ports:
        - "${PORT_DBCRYPTO}:${PORT_DBCRYPTO}"
    expose:
        - "${PORT_DBCRYPTO}"
    command: mysqld
    volumes:
      - ./database/crypto/data:/var/lib/mysql:rw
    user: "0"
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=crypto
        - MARIADB_PORT=3308
        - MARIADB_USER=monty
        - MARIADB_PASSWORD=monty
    container_name: dbcrypto
