version: '3'
services:
  weather-service:
    build: ./backend/weather
    ports:
        - "${PORT_WEATHER_SERVICE}:${PORT_WEATHER_SERVICE}"
    volumes:
        - ./backend/weather:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    container_name: weatherServcie
  crypto-service:
    build: ./backend/cryptocurrency
    ports:
        - "${PORT_CRYPTO_SERVICE}:${PORT_CRYPTO_SERVICE}"
    volumes:
        - ./backend/cryptocurrency:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    container_name: cryptoServcie
  user-service:
    build: ./backend/user
    ports:
        - "${PORT_USER_SERVICE}:${PORT_USER_SERVICE}"
    volumes:
        - ./backend/user:/usr/src/app/
        - .env:/usr/src/app/.env
    working_dir: /usr/src/app
    #environment:
    #    - MARIADB_HOST=database
    #    - MARIADB_PORT_NUMBER=3306
    #    - MARIADB_USER=monty
    #    - MARIADB_PASSWORD=monty
    #    - MARIADB_DATABASE=dashboard
    user: "1000"
    container_name: userService
    #depends_on:
        #- database
  frontend: 
    build: ./frontend
    volumes:
        - ./frontend/:/app
    ports:  
        - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    container_name: frontend
  database_user:
    build: ./database
    ports:
        - "${PORT_USER_DATABASE}:${PORT_USER_DATABASE}"
    expose:
        - "${PORT_USER_DATABASE}"
    user: "1000"
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=userdb
        - MARIADB_PORT=${PORT_USER_DATABASE}
        - MARIADB_USER=monty
        - MARIADB_PASSWORD=monty
    volumes:
      - ./database/data_user:/var/lib/mysql:rw
    container_name: database_user
